name: Fetch data
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'
jobs:
  scrape:
    name: Fetch data
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip3 install --pre -r requirements.txt
      - name: Fetch data
        run: python3 run.py
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
      - name: Commit the data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update the data"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"
          skip_dirty_check: false # Only commit if there are changes
